# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  schedule:
    # UTC 时间：每天 07:02 执行 ，北京时间：每天 15:02 执行（UTC+8）
    - cron:  '2 7 * * *'
    # UTC 时间：每天 16:02 执行，北京时间：第二天 00:02 执行（UTC+8）
    - cron:  '2 16 * * *'
    # 每天UTC时间0点2分 ，北京时间：每天 08:02 执行
    - cron:  '2 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: current date
      run: date
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "851615943@qq.com"
         git config --local user.name "kangkangding"
         git pull
         git add README.md
         git add bing-wallpaper.md
         git add picture/*
         git add docs/*
         git add zh-cn/*
         git commit -m "update readme.md"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
